<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SnoopCivil3DObjects</AssemblyName>
    <Company>Autodesk Inc.</Company>
    <Copyright>Copyright © Autodesk</Copyright>
    <OutputPath>../../</OutputPath>
    <PackageProjectUrl>https://github.com/ADN-DevTech/Civil3DSnoop</PackageProjectUrl>
    <Product>Snoop Civil3D Objects</Product>
    <RootNamespace>SnoopCivil3DObjects</RootNamespace>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <Title>Snoop Civil3D Objects</Title>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Version>1.8.0</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="AutoCAD.NET" Version="24.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Civil3D.NET" Version="13.6.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="AutoCAD.NET" Version="25.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Civil3D.NET" Version="13.7.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
